Ruslan added a json-file argument

diff --git a/bin/last-transient-slack-alert b/bin/last-transient-slack-alert
--- a/bin/last-transient-slack-alert
+++ b/bin/last-transient-slack-alert
@@ -19,6 +19,7 @@ function usage() {
         -h|--help:          Shows this help message
         -m|--message-file:  Specifies a file containing the message
         -i|--image-file:    Specifies a file containing an image with the sky-map
+        -j|--json-file:     Specifies a file containing an image with the sky-map
 
 EOF
 }
@@ -37,7 +38,7 @@ while read line; do
     eval "${line}"
 done < <(last-asroot -H $(hostname -s) --cmd "grep _proxy /etc/environment | grep _proxy" | grep -v SECT)
 
-OPTS=$( getopt -o 'hm:i:' --long "help,message-file:,image-file:" -n "${PROG}" -- "$@" )
+OPTS=$( getopt -o 'hm:i:j:' --long "help,message-file:,image-file:,json-file:" -n "${PROG}" -- "$@" )
 eval set -- "${OPTS}"
 
 while true; do
@@ -66,6 +67,15 @@ while true; do
         shift 2
         ;;
 
+    -j|--json-file)
+        if [ ! -r "${2}" ]; then
+            message_failure "Json-file \"${2}\" is not readable"
+            exit 1
+        fi
+        json_file=${2}
+        shift 2
+        ;;
+    
     --)
         shift 1
         break
@@ -145,22 +155,39 @@ message_success "API -X POST test.api worked"
 #
 # phase 3: GET files.getUploadURLExternal
 #
-bytes=$(stat --format='%s' ${image_file})
+image_file_bytes=$(stat --format='%s' ${image_file})
 out=$(slack_api \
     -F files=@${image_file} \
     -F filename=$(basename ${image_file}) \
     -F token=${SLACK_BOT_TOKEN} \
-    -F length=${bytes} \
+    -F length=${image_file_bytes} \
     files.getUploadURLExternal)
 ok=$(echo "${out}" | jq .ok)
 error=$(echo "${out}" | jq .error)
-uploadUrl=$( echo "${out}" | jq .upload_url )
-fileId=$( echo "${out}" | jq .file_id )
+image_uploadUrl=$( echo "${out}" | jq .upload_url )
+image_fileId=$( echo "${out}" | jq .file_id )
 if [ "${ok}" != true ]; then
-    message_failure "API call to files.getUploadURLExternal failed (error=${error})"
+    message_failure "API call to files.getUploadURLExternal failed for image file (error=${error})"
     exit 1
 fi
-message_success "API to files.getUploadURLExternal succeeded"
+message_success "API to files.getUploadURLExternal succeeded for image file"
+
+json_file_bytes=$(stat --format='%s' ${json_file})
+out=$(slack_api \
+    -F files=@${json_file} \
+    -F filename=$(basename ${json_file}) \
+    -F token=${SLACK_BOT_TOKEN} \
+    -F length=${json_file_bytes} \
+    files.getUploadURLExternal)
+ok=$(echo "${out}" | jq .ok)
+error=$(echo "${out}" | jq .error)
+json_uploadUrl=$( echo "${out}" | jq .upload_url )
+json_fileId=$( echo "${out}" | jq .file_id )
+if [ "${ok}" != true ]; then
+    message_failure "API call to files.getUploadURLExternal failed for json file (error=${error})"
+    exit 1
+fi
+message_success "API to files.getUploadURLExternal succeeded for json file"
 
 #
 # phase 4: upload to the received URL
@@ -169,8 +196,15 @@ out=$(slack_api \
     -X POST \
     -F token=${SLACK_BOT_TOKEN} \
     -F filename=@${image_file} \
-    ${uploadUrl//\"/})
-message_success "API to uploadUrl succeeded"
+    ${image_uploadUrl//\"/})
+message_success "API to uploadUrl succeeded for image file"
+
+out=$(slack_api \
+    -X POST \
+    -F token=${SLACK_BOT_TOKEN} \
+    -F filename=@${json_file} \
+    ${json_uploadUrl//\"/})
+message_success "API to uploadUrl succeeded for json file"
 
 #
 # phase 5: POST to files.completeUploadExternal
@@ -178,14 +212,15 @@ message_success "API to uploadUrl succeeded"
 message=$(cat ${message_file})
 message=${message//[&]/%26}
 message=${message//[+]/%20}
-fileId=${fileId//\"/}
-json="[{\"id\":\"${fileId}\",\"title\":\"NewTransient\"}]"
+image_fileId=${image_fileId//\"/}
+json_fileId=${json_fileId//\"/}
+slack_files="[{\"id\":\"${image_fileId}\",\"title\":\"NewTransientPNG\"},{\"id\":\"${json_fileId}\",\"title\":\"NewTransientJson\"}]"
 
 out=$(slack_api \
      -X POST \
      -d "token=${SLACK_BOT_TOKEN}"  \
      -H "'Content-type: application/json; charset=utf-8'" \
-     -d "files=${json}" \
+     -d "files=${slack_files}" \
      -d "initial_comment=${message}"\
      -d "channel_id=${SLACK_TRANSIENTS_CHANNEL}"\
      files.completeUploadExternal
